$terminal = kitty
$menu = rofi

xwayland {
    force_zero_scaling = true
}

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/permissions.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybindings.conf

source = ~/.config/hypr/windowsAndWorkspaces.conf
#source = ~/.config/hypr/apps.conf

source = ~/.config/hypr/lookAndFeel.conf
